# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run:  apk add ruby && gem install mustache
      # - name: creates output
      #   run:  sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@cp_instead_of_deleting
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'store'
          destination-github-username: 'RaymondMik'
          destination-repository-name: 'trashbusters-web'
          target-branch: 'main'
          user-email: ramon.miklus@gmail.com
          commit-message: See ORIGIN_COMMIT
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
    # - name: Check custom commit message
    #   uses: dmnemec/copy_file_to_another_repo_action@master
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    #   with:
    #     source_file: 'test03.md'
    #     destination_repo: 'dmnemec/release-test'
    #     user_email: 'devin.nemec@gmail.com'
    #     user_name: 'dmnemec'
    #     commit_message: 'A custom message.'
